name: test

on:
  workflow_call

env:
  POETRY_VERSION: "1.7.1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql-version:
          - "9"
          - "8"
          - "8.0.19"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    name: "test python ${{ matrix.python-version }} | mysql ${{ matrix.mysql-version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: test

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --with dev

      - name: Run tests
        shell: bash
        env:
          MYSQL_VERSIONS: ${{ matrix.mysql-version }}
        run: |
          make test

      - name: Ensure the tests did not create any additional files
        shell: bash
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
